install.packages("BiocManager")
BiocManager::install("RBGL")
install.packages("pcalg")
install.packages("kpcalg")
install.packages("MASS")
install.packages("momentchi2")
install.packages("devtools", dependencies=TRUE)
library(devtools)
install_github("Diviyan-Kalainathan/RCIT")
library(RCIT)
